// <auto-generated />
using System;
using ClsAppEntityFrameworkCore21.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClsAppEntityFrameworkCore21.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029");

            modelBuilder.Entity("ClsAppEntityFrameworkCore21.Models.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("people");

                    b.HasData(
                        new { Id = 1, Created = new DateTime(2018, 5, 7, 11, 16, 8, 377, DateTimeKind.Local), Name = "Example 1" },
                        new { Id = 2, Created = new DateTime(2018, 5, 6, 11, 16, 8, 379, DateTimeKind.Local), Name = "Example 2" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
